name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_deploy:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          repository: n4-t3/React-Clock

      - name: install packages
        run: npm install

      - name: run test
        run: npm run test

      - name: test build
        run: npm run build

      - name: Deploy to gh pages
        run: npm run deploy
        with: 
          target_branch: gh-pages
          build_dir: build

