name: CI
on: 
  [push, pull_request]:
    branches:
      - main
jobs:
  test:
    runs-on: [ 'ubuntu-latest', 'windows-latest' ]
    steps:
      - name: package install
        uses: actions/checkout@v3
      - run: npm install

      - name: run test
        run: npm run test

  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Deploy to gh pages
        uses: action/checkout@v3
      - run: npm install
      - npm: npm run deploy
