name: CI -> Merge -> CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Run test
        run: npm test

  merge_and_deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.ref == 'refs/heads/develop') || (github.event_name == 'push' && github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if it's a pull request or a direct push to develop
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Automatically merge the PR
            gh pr merge ${{ github.event.number }} --auto --delete-branch

            # Deploy to GitHub Pages
            npm install
            npm run build
            echo "n4-t3.github.io/React-Clock" > ./build/CNAME
            npx gh-pages -d build -b gh-pages
            
          elif [ "${{ github.event_name }}" == "push" ]; then
            # Deploy to GitHub Pages for direct pushes to 'develop'
            npm install
            npm run build
            echo "n4-t3.github.io/React-Clock" > ./build/CNAME
            npx gh-pages -d build -b gh-pages
          fi
