name: CI -> Merge -> CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Run test
        run: npm test

  merge_and_deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.ref != 'refs/heads/main') || (github.event_name == 'push' && github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge if PR to Develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch ${{ github.ref }}
          fi

      - name: Deploy with gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install 
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
