name: Merge PR on CI Success

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR on CI Success
        uses: phillipj/git-merge-on-success@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
